#!/bin/bash
# ============================================================
# infrastructure/push_images.sh
#
# WHAT: Builds Docker images for linux/amd64, tags them with
#       the ECR repository URIs, and pushes them to ECR.
#
# WHY:  ECS Fargate runs on AWS's x86_64 (amd64) infrastructure.
#       If you're developing on an Apple Silicon Mac (M1/M2/M3),
#       your default Docker builds target arm64, which WILL NOT
#       run on ECS. We force --platform=linux/amd64 to cross-
#       compile the images before pushing.
#
#       Docker BuildKit (used via `docker buildx`) handles the
#       cross-compilation transparently using QEMU emulation.
#
# PREREQS:
#   - ecr_setup.sh must have been run (creates .ecr_env file)
#   - Docker Desktop must be running
#   - AWS CLI must be configured
#
# USAGE:
#   bash infrastructure/push_images.sh
#   # Or override defaults:
#   AWS_REGION=us-west-2 bash infrastructure/push_images.sh
# ============================================================

set -euo pipefail

# ── ANSI colors ───────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ── Load ECR environment created by ecr_setup.sh ──────────────
# The .ecr_env file contains AWS_ACCOUNT_ID, AWS_REGION, and
# repository URIs so we don't have to re-enter them manually.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ECR_ENV_FILE="${PROJECT_DIR}/.ecr_env"

echo -e "${BLUE}══════════════════════════════════════════${NC}"
echo -e "${BLUE}  Docker → ECR Push — AI Platform         ${NC}"
echo -e "${BLUE}══════════════════════════════════════════${NC}"
echo ""

if [[ -f "$ECR_ENV_FILE" ]]; then
    echo -e "${CYAN}Loading ECR environment from .ecr_env...${NC}"
    # shellcheck source=/dev/null
    source "$ECR_ENV_FILE"
else
    echo -e "${YELLOW}WARNING: .ecr_env not found. Using environment variables.${NC}"
    echo "Run infrastructure/ecr_setup.sh first, or set:"
    echo "  AWS_ACCOUNT_ID, AWS_REGION, API_REPO_URI, UI_REPO_URI"
fi

# ── Configuration (can override via environment variables) ─────
AWS_REGION="${AWS_REGION:-us-east-1}"
AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-}"

# Construct the ECR registry URL.
# Pattern: <account_id>.dkr.ecr.<region>.amazonaws.com
# Every push to this registry endpoint goes into your account's ECR.
ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

# Image names: repo_uri:tag
# The :latest tag is the default. In production you'd use a git
# commit SHA for immutable, auditable image versioning.
API_IMAGE="${API_REPO_URI:-${ECR_REGISTRY}/ai-platform-api}:latest"
UI_IMAGE="${UI_REPO_URI:-${ECR_REGISTRY}/ai-platform-ui}:latest"

# Path to the Phase 6 Project 01 Docker setup where our
# Dockerfiles and application code live.
DOCKER_PROJECT_DIR="${DOCKER_PROJECT_DIR:-${PROJECT_DIR}/../project_01_docker_setup}"

echo -e "${CYAN}  ECR Registry: ${ECR_REGISTRY}${NC}"
echo -e "${CYAN}  API Image:    ${API_IMAGE}${NC}"
echo -e "${CYAN}  UI Image:     ${UI_IMAGE}${NC}"
echo -e "${CYAN}  Source Dir:   ${DOCKER_PROJECT_DIR}${NC}"
echo ""

# ── Step 1: Verify prerequisites ──────────────────────────────
echo -e "${YELLOW}[1/5] Verifying prerequisites...${NC}"

# Check Docker is installed and the daemon is running.
if ! command -v docker &>/dev/null; then
    echo -e "${RED}ERROR: Docker not found. Install Docker Desktop.${NC}"
    exit 1
fi

# 'docker info' fails if the Docker daemon isn't running.
if ! docker info &>/dev/null; then
    echo -e "${RED}ERROR: Docker daemon is not running.${NC}"
    echo "Start Docker Desktop and try again."
    exit 1
fi

if [[ -z "$AWS_ACCOUNT_ID" ]]; then
    echo -e "${RED}ERROR: AWS_ACCOUNT_ID is not set.${NC}"
    echo "Run ecr_setup.sh first, or: export AWS_ACCOUNT_ID=\$(aws sts get-caller-identity --query Account --output text)"
    exit 1
fi

echo -e "${GREEN}  ✓ Docker daemon running${NC}"
echo -e "${GREEN}  ✓ AWS Account ID: ${AWS_ACCOUNT_ID}${NC}"

# ── Step 2: Authenticate Docker to ECR ────────────────────────
# ECR uses temporary passwords (valid 12 hours) generated by AWS.
# The flow is:
#   aws ecr get-login-password  → outputs a short-lived token
#   docker login                → authenticates using that token
#
# After this, 'docker push' to the ECR registry will work.
echo -e "${YELLOW}[2/5] Authenticating Docker to ECR...${NC}"

aws ecr get-login-password --region "$AWS_REGION" | \
    docker login \
        --username AWS \
        --password-stdin \
        "${ECR_REGISTRY}"

echo -e "${GREEN}  ✓ Docker authenticated to ECR${NC}"

# ── Step 3: Build API image (linux/amd64) ─────────────────────
# --platform linux/amd64
#   Forces cross-compilation for x86_64. Critical on Apple Silicon
#   Macs where the native platform is linux/arm64. ECS Fargate
#   (without Graviton) runs on x86_64 only.
#
# --file / -f
#   Specifies which Dockerfile to use. If your Dockerfiles are
#   named Dockerfile.api and Dockerfile.ui (common in monorepos),
#   adjust the -f path accordingly.
#
# --tag / -t
#   Sets the full image name including the ECR URI so 'docker push'
#   knows exactly where to send the image.
echo -e "${YELLOW}[3/5] Building API image for linux/amd64...${NC}"
echo -e "${CYAN}  This may take several minutes on first build.${NC}"
echo -e "${CYAN}  Subsequent builds use layer cache and are faster.${NC}"

docker buildx build \
    --platform linux/amd64 \
    --file "${DOCKER_PROJECT_DIR}/Dockerfile.api" \
    --tag "${API_IMAGE}" \
    --load \
    "${DOCKER_PROJECT_DIR}"

# --load: saves the built image into the local Docker image store
# so we can push it. Without --load, buildx discards the image
# after building (it's designed for multi-platform manifests).

echo -e "${GREEN}  ✓ API image built: ${API_IMAGE}${NC}"

# ── Step 4: Build UI image (linux/amd64) ──────────────────────
echo -e "${YELLOW}[4/5] Building UI image for linux/amd64...${NC}"

docker buildx build \
    --platform linux/amd64 \
    --file "${DOCKER_PROJECT_DIR}/Dockerfile.ui" \
    --tag "${UI_IMAGE}" \
    --load \
    "${DOCKER_PROJECT_DIR}"

echo -e "${GREEN}  ✓ UI image built: ${UI_IMAGE}${NC}"

# ── Step 5: Push both images to ECR ───────────────────────────
# 'docker push' transfers image layers to ECR.
# ECR deduplicates layers — if two images share a base layer
# (e.g., both use python:3.11-slim), it's only stored once.
# This saves storage cost and speeds up ECS pulls.
echo -e "${YELLOW}[5/5] Pushing images to ECR...${NC}"

echo -e "${CYAN}  Pushing API image...${NC}"
docker push "${API_IMAGE}"
echo -e "${GREEN}  ✓ API image pushed${NC}"

echo -e "${CYAN}  Pushing UI image...${NC}"
docker push "${UI_IMAGE}"
echo -e "${GREEN}  ✓ UI image pushed${NC}"

# ── Summary ────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}══════════════════════════════════════════${NC}"
echo -e "${GREEN}  Images pushed successfully to ECR!${NC}"
echo -e "${BLUE}══════════════════════════════════════════${NC}"
echo ""
echo "  Full image URIs (use these in Terraform variables):"
echo ""
echo -e "  ${CYAN}api_image_uri${NC} = \"${API_IMAGE}\""
echo -e "  ${CYAN}ui_image_uri${NC}  = \"${UI_IMAGE}\""
echo ""
echo "  Verify in AWS Console:"
echo "  https://console.aws.amazon.com/ecr/repositories?region=${AWS_REGION}"
echo ""
